import type { AliasToken, DialogToken } from '../theme'

export function getDialogToken(token: AliasToken): DialogToken {
  return {
    width: 320,
    smallScreenWidth: '90%',
    backgroundColor: token.colorBgElevated,
    overlayColor: token.colorBgMask,
    borderRadius: token.borderRadiusLG * 2,
    titleColor: token.colorText,
    messageColor: token.colorText,
    messageHasTitleColor: token.colorTextSecondary,
    fontSize: token.fontSize,
    titleFontSize: token.fontSizeLG,
    titleLineHeight: token.lineHeightLG,
    messageLineHeight: token.lineHeight,
    headerFontWeight: '600',
    headerPaddingTop: token.paddingLG + 2,
    headerPaddingHorizontal: token.paddingLG,
    headerPaddingBottom: token.paddingXS,
    headerIsolatedPaddingTop: token.paddingLG,
    headerIsolatedPaddingBottom: token.paddingLG,
    headerIsolatedPaddingHorizontal: token.paddingLG,
    messagePaddingHorizontal: token.paddingLG,
    messagePaddingTop: token.paddingXS,
    messagePaddingBottom: token.paddingLG,
    messageMaxHeightRatio: 0.6,
    buttonHeight: token.controlHeight + token.sizeUnit,
    roundButtonHeight: Math.max(token.controlHeight - token.sizeUnit * 2, token.controlHeightXS),
    buttonFontSize: token.fontSizeLG,
    buttonPressedOverlayColor: token.pressedOverlayColor,
    buttonDisabledOpacity: 0.5,
    confirmButtonColor: token.colorPrimary,
    cancelButtonColor: token.colorText,
    dividerColor: token.colorBorderSecondary,
    dividerWidth: token.lineWidthHairline,
    buttonGap: token.paddingSM,
    footerPaddingHorizontal: token.paddingLG,
    footerPaddingVertical: token.paddingSM,
    animationDuration: Math.max(0, token.motionDurationMid),
    zIndex: token.zIndexPopupBase + 1000,
    fontFamily: token.fontFamily,
  }
}
