import type { AliasToken, DropdownToken } from '../theme'

export function getDropdownToken(token: AliasToken): DropdownToken {
  return {
    menuHeight: 48,
    menuBackgroundColor: token.colorBgContainer,
    titleColor: token.colorText,
    activeColor: token.colorPrimary,
    disabledColor: token.colorTextDisabled,
    optionTextColor: token.colorText,
    optionDisabledColor: token.colorTextDisabled,
    optionPressedBackgroundColor: token.pressedBackgroundColor,
    titleFontSize: 15,
    titleLineHeight: token.lineHeight,
    titleFontFamily: token.fontFamily,
    caretSize: 4,
    caretGap: token.sizeXXS,
    optionHeight: 44,
    optionPaddingHorizontal: token.padding,
    optionFontSize: token.fontSize,
    optionLineHeight: token.lineHeight,
    optionIconSize: token.fontSizeLG,
    contentBackgroundColor: token.colorBgContainer,
    dividerColor: token.colorBorderSecondary,
    dividerWidth: token.lineWidthHairline,
    shadowColor: token.colorShadow,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: 2,
    elevation: 4,
    overlayColor: token.colorBgMask,
    animationDuration: Math.max(0, token.motionDurationMid),
    zIndex: token.zIndexPopupBase,
  }
}
