// This file is generated by scripts/generate-fixture-catalog.cjs.
import type { ComponentType } from 'react'

import Fixture0 from '../../src/avatar/__fixtures__/examples/basic'
import Fixture1 from '../../src/avatar/__fixtures__/examples/group'
import Fixture2 from '../../src/avatar/__fixtures__/examples/sources'
import Fixture3 from '../../src/avatar/__fixtures__/overview'
import Fixture4 from '../../src/badge/__fixtures__/examples/status'
import Fixture5 from '../../src/badge/__fixtures__/examples/theme'
import Fixture6 from '../../src/badge/__fixtures__/examples/types'
import Fixture7 from '../../src/badge/__fixtures__/overview'
import Fixture8 from '../../src/button/__fixtures__/variants'
import Fixture9 from '../../src/cell/__fixtures__/basic'
import Fixture10 from '../../src/dialog/__fixtures__/examples/basic'
import Fixture11 from '../../src/dialog/__fixtures__/examples/before-close'
import Fixture12 from '../../src/dialog/__fixtures__/examples/confirm'
import Fixture13 from '../../src/dialog/__fixtures__/examples/controlled'
import Fixture14 from '../../src/dialog/__fixtures__/examples/custom'
import Fixture15 from '../../src/dialog/__fixtures__/examples/interactions'
import Fixture16 from '../../src/dialog/__fixtures__/examples/round'
import Fixture17 from '../../src/dialog/__fixtures__/examples/theme'
import Fixture18 from '../../src/dialog/__fixtures__/overview'
import Fixture19 from '../../src/floating-panel/__fixtures__/examples/anchors'
import Fixture20 from '../../src/floating-panel/__fixtures__/examples/basic'
import Fixture21 from '../../src/floating-panel/__fixtures__/examples/content-draggable'
import Fixture22 from '../../src/floating-panel/__fixtures__/examples/disabled'
import Fixture23 from '../../src/floating-panel/__fixtures__/examples/magnetic'
import Fixture24 from '../../src/floating-panel/__fixtures__/examples/safe-area'
import Fixture25 from '../../src/floating-panel/__fixtures__/examples/theme'
import Fixture26 from '../../src/floating-panel/__fixtures__/overview'
import Fixture27 from '../../src/grid/__fixtures__/basic'
import Fixture28 from '../../src/icon/__fixtures__/basic'
import Fixture29 from '../../src/loading/__fixtures__/basic'
import Fixture30 from '../../src/overlay/__fixtures__/examples/basic'
import Fixture31 from '../../src/overlay/__fixtures__/examples/embedded'
import Fixture32 from '../../src/overlay/__fixtures__/examples/interactions'
import Fixture33 from '../../src/overlay/__fixtures__/examples/theme'
import Fixture34 from '../../src/overlay/__fixtures__/overview'
import Fixture35 from '../../src/popup/__fixtures__/examples/basic'
import Fixture36 from '../../src/popup/__fixtures__/examples/interactions'
import Fixture37 from '../../src/popup/__fixtures__/examples/lifecycle'
import Fixture38 from '../../src/popup/__fixtures__/examples/positions'
import Fixture39 from '../../src/popup/__fixtures__/examples/theme'
import Fixture40 from '../../src/popup/__fixtures__/overview'
import Fixture41 from '../../src/portal/__fixtures__/examples/basic'
import Fixture42 from '../../src/portal/__fixtures__/examples/imperative'
import Fixture43 from '../../src/portal/__fixtures__/overview'
import Fixture44 from '../../src/provider/__fixtures__/examples/basic'
import Fixture45 from '../../src/provider/__fixtures__/overview'
import Fixture46 from '../../src/radio/__fixtures__/examples/disabled'
import Fixture47 from '../../src/radio/__fixtures__/examples/group'
import Fixture48 from '../../src/radio/__fixtures__/examples/options'
import Fixture49 from '../../src/radio/__fixtures__/examples/shapes'
import Fixture50 from '../../src/radio/__fixtures__/examples/standalone'
import Fixture51 from '../../src/radio/__fixtures__/examples/styled'
import Fixture52 from '../../src/radio/__fixtures__/examples/theme'
import Fixture53 from '../../src/radio/__fixtures__/overview'
import Fixture54 from '../../src/text-input/__fixtures__/basic'
import Fixture55 from '../../src/text/__fixtures__/examples/basic'
import Fixture56 from '../../src/text/__fixtures__/examples/semantic'
import Fixture57 from '../../src/text/__fixtures__/overview'
import Fixture58 from '../../src/theme/__fixtures__/algorithms'
import Fixture59 from '../../src/toast/__fixtures__/examples/basic'
import Fixture60 from '../../src/toast/__fixtures__/examples/controlled'
import Fixture61 from '../../src/toast/__fixtures__/examples/interactions'
import Fixture62 from '../../src/toast/__fixtures__/examples/multiple'
import Fixture63 from '../../src/toast/__fixtures__/examples/positions'
import Fixture64 from '../../src/toast/__fixtures__/examples/theme'
import Fixture65 from '../../src/toast/__fixtures__/overview'

export interface FixtureEntry {
  Component: ComponentType
  component: string
  description: string
  id: string
  title: string
}

export const fixtureCatalog: readonly FixtureEntry[] = [
  {
    Component: Fixture0,
    component: 'avatar',
    description:
      'Avatar 支持 small、medium、large 和自定义数值尺寸，并可切换圆形、方形或自定义圆角。',
    id: 'avatar/examples/basic',
    title: '尺寸和形状',
  },
  {
    Component: Fixture1,
    component: 'avatar',
    description: 'Group 会叠放直接子级 Avatar，maxCount 超出后显示可点击的 +N 头像。',
    id: 'avatar/examples/group',
    title: 'Avatar.Group',
  },
  {
    Component: Fixture2,
    component: 'avatar',
    description:
      '图片加载失败时按 icon、children 的顺序回退；图片地址支持字符串或 RN Image source。',
    id: 'avatar/examples/sources',
    title: '图片、图标和字符',
  },
  {
    Component: Fixture3,
    component: 'avatar',
    description: 'Overview',
    id: 'avatar/overview',
    title: '组件预览',
  },
  {
    Component: Fixture4,
    component: 'badge',
    description: 'status 用于展示成功、处理中、默认、错误和警告状态，也可以附带文字。',
    id: 'badge/examples/status',
    title: '状态点',
  },
  {
    Component: Fixture5,
    component: 'badge',
    description: 'Badge 支持组件 token 和 root、indicator、dot、text 语义样式。',
    id: 'badge/examples/theme',
    title: '主题和语义样式',
  },
  {
    Component: Fixture6,
    component: 'badge',
    description: 'count 支持数字和自定义节点，数字超过 overflowCount 时显示封顶值。',
    id: 'badge/examples/types',
    title: '数字、红点和溢出',
  },
  {
    Component: Fixture7,
    component: 'badge',
    description: 'Overview',
    id: 'badge/overview',
    title: '组件预览',
  },
  {
    Component: Fixture8,
    component: 'button',
    description: 'Check the common button types, states, sizes and semantic slots.',
    id: 'button/variants',
    title: 'Button variants',
  },
  {
    Component: Fixture9,
    component: 'cell',
    description: 'Render grouped cells with labels, links, required markers and custom content.',
    id: 'cell/basic',
    title: 'Cell groups and interactions',
  },
  {
    Component: Fixture10,
    component: 'dialog',
    description: 'showDialog 默认展示一个确认按钮，Promise 在确认后 resolve。',
    id: 'dialog/examples/basic',
    title: '基础提示',
  },
  {
    Component: Fixture11,
    component: 'dialog',
    description: 'beforeClose 可以执行异步检查；返回 false 时保持 Dialog 打开并清除按钮 loading。',
    id: 'dialog/examples/before-close',
    title: '异步关闭',
  },
  {
    Component: Fixture12,
    component: 'dialog',
    description: 'showConfirmDialog 增加取消按钮，确认和取消分别对应 Promise 的 resolve/reject。',
    id: 'dialog/examples/confirm',
    title: '确认框',
  },
  {
    Component: Fixture13,
    component: 'dialog',
    description: '直接使用 Dialog，通过 show 和 onShowChange 管理显示状态。',
    id: 'dialog/examples/controlled',
    title: '受控组件',
  },
  {
    Component: Fixture14,
    component: 'dialog',
    description: 'children 替换 message，footer 替换默认按钮区域，title 也支持 ReactNode。',
    id: 'dialog/examples/custom',
    title: '自定义内容',
  },
  {
    Component: Fixture15,
    component: 'dialog',
    description: 'closeOnClickOverlay 开启后可点击遮罩关闭，也可以分别禁用确认和取消按钮。',
    id: 'dialog/examples/interactions',
    title: '遮罩与禁用',
  },
  {
    Component: Fixture16,
    component: 'dialog',
    description: 'theme="round-button" 使用 Vant 风格的圆角操作按钮。',
    id: 'dialog/examples/round',
    title: '圆角按钮',
  },
  {
    Component: Fixture17,
    component: 'dialog',
    description: '通过 Dialog token 和 semantic styles 定制面板、按钮和正文样式。',
    id: 'dialog/examples/theme',
    title: '主题定制',
  },
  {
    Component: Fixture18,
    component: 'dialog',
    description: 'Overview',
    id: 'dialog/overview',
    title: '组件预览',
  },
  {
    Component: Fixture19,
    component: 'floating-panel',
    description: 'anchors 定义停靠位置，height 与 onHeightChange 可用于实时展示当前面板高度。',
    id: 'floating-panel/examples/anchors',
    title: '自定义锚点',
  },
  {
    Component: Fixture20,
    component: 'floating-panel',
    description: 'FloatingPanel 默认从 100px 高度开始，可在默认最大高度和最小高度之间拖动。',
    id: 'floating-panel/examples/basic',
    title: '基础用法',
  },
  {
    Component: Fixture21,
    component: 'floating-panel',
    description:
      'contentDraggable=false 时，面板只能通过 header 拖动，内容区域保留 ScrollView 滚动。',
    id: 'floating-panel/examples/content-draggable',
    title: '仅拖动头部',
  },
  {
    Component: Fixture22,
    component: 'floating-panel',
    description: 'draggable=false 会隐藏默认拖拽条并固定面板高度，内容仍可滚动。',
    id: 'floating-panel/examples/disabled',
    title: '禁用拖动',
  },
  {
    Component: Fixture23,
    component: 'floating-panel',
    description: 'magnetic=false 时，面板松手后停留在边界内的实际高度，不会吸附到锚点。',
    id: 'floating-panel/examples/magnetic',
    title: '关闭磁吸',
  },
  {
    Component: Fixture24,
    component: 'floating-panel',
    description: 'safeAreaInsetBottom 默认开启，只增加内容底部 padding，不改变面板锚点高度。',
    id: 'floating-panel/examples/safe-area',
    title: '底部安全区',
  },
  {
    Component: Fixture25,
    component: 'floating-panel',
    description: '通过 FloatingPanel token 和 semantic styles 定制面板背景、圆角和拖拽条。',
    id: 'floating-panel/examples/theme',
    title: '主题定制',
  },
  {
    Component: Fixture26,
    component: 'floating-panel',
    description: 'Overview',
    id: 'floating-panel/overview',
    title: '组件预览',
  },
  {
    Component: Fixture27,
    component: 'grid',
    description: 'Use a 24-column row with gaps and offsets.',
    id: 'grid/basic',
    title: 'Grid layout',
  },
  {
    Component: Fixture28,
    component: 'icon',
    description: 'Use Ant Design SVG definitions with native-style size, color and touch targets.',
    id: 'icon/basic',
    title: 'Icon gallery',
  },
  {
    Component: Fixture29,
    component: 'loading',
    description: 'Preview loading indicators with different sizes and colors.',
    id: 'loading/basic',
    title: 'LoadingIcon',
  },
  {
    Component: Fixture30,
    component: 'overlay',
    description: '使用 show 控制遮罩显示，点击遮罩后由调用方关闭组件。',
    id: 'overlay/examples/basic',
    title: '基础用法',
  },
  {
    Component: Fixture31,
    component: 'overlay',
    description: 'children 会显示在遮罩上方，可放置按钮等交互内容。',
    id: 'overlay/examples/embedded',
    title: '嵌入内容',
  },
  {
    Component: Fixture32,
    component: 'overlay',
    description: 'backgroundColor 可以设为 transparent，duration 使用毫秒并支持受控开关。',
    id: 'overlay/examples/interactions',
    title: '透明遮罩与动画',
  },
  {
    Component: Fixture33,
    component: 'overlay',
    description: '通过 Overlay token 和 semantic styles 定制遮罩与内容区域。',
    id: 'overlay/examples/theme',
    title: '主题定制',
  },
  {
    Component: Fixture34,
    component: 'overlay',
    description: 'Overview',
    id: 'overlay/overview',
    title: '组件预览',
  },
  {
    Component: Fixture35,
    component: 'popup',
    description: 'Popup 通过 visible 受控显示，默认居中并使用 PortalHost 承载浮层。',
    id: 'popup/examples/basic',
    title: '基础用法',
  },
  {
    Component: Fixture36,
    component: 'popup',
    description:
      'overlay 控制遮罩，onPressOverlay 监听点击，closeOnPressOverlay 发出受控关闭请求。',
    id: 'popup/examples/interactions',
    title: '遮罩交互',
  },
  {
    Component: Fixture37,
    component: 'popup',
    description: 'lazyRender 延迟首次渲染，destroyOnClosed 在关闭动画完成后卸载内容。',
    id: 'popup/examples/lifecycle',
    title: '生命周期与销毁',
  },
  {
    Component: Fixture38,
    component: 'popup',
    description: 'position 支持 center、top、bottom、left 和 right，round 会按位置裁剪对应圆角。',
    id: 'popup/examples/positions',
    title: '五种位置',
  },
  {
    Component: Fixture39,
    component: 'popup',
    description: '通过 Popup token 和 semantic styles 定制面板、遮罩和宿主层。',
    id: 'popup/examples/theme',
    title: '主题定制',
  },
  {
    Component: Fixture40,
    component: 'popup',
    description: 'Overview',
    id: 'popup/overview',
    title: '组件预览',
  },
  {
    Component: Fixture41,
    component: 'portal',
    description: 'Portal 会将内容渲染到 PortalHost 的宿主层。',
    id: 'portal/examples/basic',
    title: '组件式 Portal',
  },
  {
    Component: Fixture42,
    component: 'portal',
    description: '使用 PortalKey 更新或卸载由 mountPortal 创建的 entry。',
    id: 'portal/examples/imperative',
    title: '命令式挂载',
  },
  {
    Component: Fixture43,
    component: 'portal',
    description: 'Overview',
    id: 'portal/overview',
    title: '组件预览',
  },
  {
    Component: Fixture44,
    component: 'provider',
    description: 'Wrap the application once to provide shared theme and portal context.',
    id: 'provider/examples/basic',
    title: 'Application entry',
  },
  {
    Component: Fixture45,
    component: 'provider',
    description: 'Provider supplies the application-level context and portal host.',
    id: 'provider/overview',
    title: 'Provider overview',
  },
  {
    Component: Fixture46,
    component: 'radio',
    description: 'Radio 自身、options 选项和整个 Radio.Group 都可以禁用。',
    id: 'radio/examples/disabled',
    title: '禁用状态',
  },
  {
    Component: Fixture47,
    component: 'radio',
    description: '使用子 Radio 自定义每个选项，支持受控值、默认值、横向布局和间距。',
    id: 'radio/examples/group',
    title: 'Radio.Group 子节点',
  },
  {
    Component: Fixture48,
    component: 'radio',
    description: '使用 options 快速生成选项，适合标签简单且结构一致的单选组。',
    id: 'radio/examples/options',
    title: 'options 分组',
  },
  {
    Component: Fixture49,
    component: 'radio',
    description: 'shape 支持圆形和方形指示器，labelPosition 可将标签放到左侧。',
    id: 'radio/examples/shapes',
    title: '指示器形状',
  },
  {
    Component: Fixture50,
    component: 'radio',
    description: 'standalone Radio 支持受控和非受控两种写法，选中后不会通过再次点击取消。',
    id: 'radio/examples/standalone',
    title: '独立 Radio',
  },
  {
    Component: Fixture51,
    component: 'radio',
    description: 'children 支持自定义节点，styles 可分别覆盖 root、indicator 和 label。',
    id: 'radio/examples/styled',
    title: '自定义内容与语义样式',
  },
  {
    Component: Fixture52,
    component: 'radio',
    description: '通过 ConfigProvider 的 theme.components.Radio 统一调整指示器和间距 token。',
    id: 'radio/examples/theme',
    title: '主题定制',
  },
  {
    Component: Fixture53,
    component: 'radio',
    description: 'Overview',
    id: 'radio/overview',
    title: '组件预览',
  },
  {
    Component: Fixture54,
    component: 'text-input',
    description: 'Try controlled text input, clearable textarea and word-limit feedback.',
    id: 'text-input/basic',
    title: 'TextInput states',
  },
  {
    Component: Fixture55,
    component: 'text',
    description: '默认文本自动使用当前主题的 colorText，显式 style 可以覆盖主题颜色。',
    id: 'text/examples/basic',
    title: '基础文本',
  },
  {
    Component: Fixture56,
    component: 'text',
    description: '使用 type、size 和 weight 表达移动端常见的文本层级，不提供 Heading 体系。',
    id: 'text/examples/semantic',
    title: '语义、尺寸和字重',
  },
  {
    Component: Fixture57,
    component: 'text',
    description: 'Overview',
    id: 'text/overview',
    title: 'Overview',
  },
  {
    Component: Fixture58,
    component: 'theme',
    description: 'Switch between light and dark algorithms and inspect a component token override.',
    id: 'theme/algorithms',
    title: 'Theme algorithms and overrides',
  },
  {
    Component: Fixture59,
    component: 'toast',
    description: 'Toast 支持 text、loading、success 和 fail 四种原生提示类型。',
    id: 'toast/examples/basic',
    title: '基础类型',
  },
  {
    Component: Fixture60,
    component: 'toast',
    description: '直接使用 Toast，通过 show 和 onShowChange 管理显示状态。',
    id: 'toast/examples/controlled',
    title: '受控组件',
  },
  {
    Component: Fixture61,
    component: 'toast',
    description:
      'duration 为 0 时保持显示，可通过实例 close、closeToast、overlay 和 forbidClick 控制生命周期与触摸行为。',
    id: 'toast/examples/interactions',
    title: '持续显示与交互',
  },
  {
    Component: Fixture62,
    component: 'toast',
    description: '默认新提示会更新当前实例，开启 allowMultipleToast 后可以同时展示多个提示。',
    id: 'toast/examples/multiple',
    title: '单例与多实例',
  },
  {
    Component: Fixture63,
    component: 'toast',
    description: '使用 position 将提示放在顶部、中间或底部。',
    id: 'toast/examples/positions',
    title: '位置',
  },
  {
    Component: Fixture64,
    component: 'toast',
    description: '通过 ConfigProvider 的 Toast token 和 semantic styles 定制外观。',
    id: 'toast/examples/theme',
    title: '主题定制',
  },
  {
    Component: Fixture65,
    component: 'toast',
    description: 'Overview',
    id: 'toast/overview',
    title: '组件预览',
  },
]
