// This file is generated by scripts/generate-fixture-catalog.cjs.
import type { ComponentType } from 'react'

import ComponentOverview0 from '../../src/action-sheet/__fixtures__/overview'
import ComponentOverview1 from '../../src/avatar/__fixtures__/overview'
import ComponentOverview2 from '../../src/badge/__fixtures__/overview'
import ComponentOverview3 from '../../src/bottom-bar/__fixtures__/overview'
import ComponentOverview4 from '../../src/button/__fixtures__/overview'
import ComponentOverview5 from '../../src/cell/__fixtures__/overview'
import ComponentOverview6 from '../../src/checkbox/__fixtures__/overview'
import ComponentOverview7 from '../../src/collapse/__fixtures__/overview'
import ComponentOverview8 from '../../src/dialog/__fixtures__/overview'
import ComponentOverview9 from '../../src/divider/__fixtures__/overview'
import ComponentOverview10 from '../../src/empty/__fixtures__/overview'
import ComponentOverview11 from '../../src/field/__fixtures__/overview'
import ComponentOverview12 from '../../src/floating-panel/__fixtures__/overview'
import ComponentOverview13 from '../../src/gesture/__fixtures__/overview'
import ComponentOverview14 from '../../src/grid/__fixtures__/overview'
import ComponentOverview15 from '../../src/icon/__fixtures__/overview'
import ComponentOverview16 from '../../src/input/__fixtures__/overview'
import ComponentOverview17 from '../../src/loading/__fixtures__/overview'
import ComponentOverview18 from '../../src/motion/__fixtures__/overview'
import ComponentOverview19 from '../../src/navbar/__fixtures__/overview'
import ComponentOverview20 from '../../src/notice-bar/__fixtures__/overview'
import ComponentOverview21 from '../../src/overlay/__fixtures__/overview'
import ComponentOverview22 from '../../src/picker/__fixtures__/overview'
import ComponentOverview23 from '../../src/popup/__fixtures__/overview'
import ComponentOverview24 from '../../src/portal/__fixtures__/overview'
import ComponentOverview25 from '../../src/pressable/__fixtures__/overview'
import ComponentOverview26 from '../../src/progress/__fixtures__/overview'
import ComponentOverview27 from '../../src/provider/__fixtures__/overview'
import ComponentOverview28 from '../../src/radio/__fixtures__/overview'
import ComponentOverview29 from '../../src/search/__fixtures__/overview'
import ComponentOverview30 from '../../src/segmented/__fixtures__/overview'
import ComponentOverview31 from '../../src/surface/__fixtures__/overview'
import ComponentOverview32 from '../../src/swipe-cell/__fixtures__/overview'
import ComponentOverview33 from '../../src/switch/__fixtures__/overview'
import ComponentOverview34 from '../../src/tabs/__fixtures__/overview'
import ComponentOverview35 from '../../src/text/__fixtures__/overview'
import ComponentOverview36 from '../../src/text-input/__fixtures__/overview'
import ComponentOverview37 from '../../src/theme/__fixtures__/overview'
import ComponentOverview38 from '../../src/time-picker/__fixtures__/overview'
import ComponentOverview39 from '../../src/toast/__fixtures__/overview'

export interface ComponentFixtureEntry {
  Component: ComponentType
  component: string
  description: string
  id: string
  title: string
}

export const componentCatalog: readonly ComponentFixtureEntry[] = [
  {
    Component: ComponentOverview0,
    component: 'action-sheet',
    description: 'ActionSheet 的基础菜单、状态和自定义内容预览。',
    id: 'action-sheet',
    title: 'ActionSheet',
  },
  {
    Component: ComponentOverview1,
    component: 'avatar',
    description: 'Avatar 汇总尺寸、形状、来源、分组和角标组合示例。',
    id: 'avatar',
    title: 'Avatar',
  },
  {
    Component: ComponentOverview2,
    component: 'badge',
    description: 'Badge 汇总数字、红点、状态和主题样式示例。',
    id: 'badge',
    title: 'Badge',
  },
  {
    Component: ComponentOverview3,
    component: 'bottom-bar',
    description: 'BottomBar 提供页面底部固定布局，可承载按钮组、输入框和任意操作内容。',
    id: 'bottom-bar',
    title: 'BottomBar',
  },
  {
    Component: ComponentOverview4,
    component: 'button',
    description: 'Button 的类型、状态和形状预览。',
    id: 'button',
    title: 'Button',
  },
  {
    Component: ComponentOverview5,
    component: 'cell',
    description: 'Cell 和 CellGroup 的 Vant 基线用法预览。',
    id: 'cell',
    title: 'Cell',
  },
  {
    Component: ComponentOverview6,
    component: 'checkbox',
    description: 'Checkbox 汇总基础状态、多选分组、button variant 和主题定制示例。',
    id: 'checkbox',
    title: 'Checkbox',
  },
  {
    Component: ComponentOverview7,
    component: 'collapse',
    description: 'Collapse 的基础、手风琴、默认展开、禁用、受控和主题示例。',
    id: 'collapse',
    title: 'Collapse',
  },
  {
    Component: ComponentOverview8,
    component: 'dialog',
    description: 'Dialog 通过 selector 汇总各种交互和样式示例，每次只挂载一个浮层。',
    id: 'dialog',
    title: 'Dialog',
  },
  {
    Component: ComponentOverview9,
    component: 'divider',
    description: 'Divider 的横向 hairline、颜色、厚度和左右 inset 示例。',
    id: 'divider',
    title: 'Divider',
  },
  {
    Component: ComponentOverview10,
    component: 'empty',
    description: 'Empty 汇总默认空状态、描述、图片、底部操作区域和主题定制示例。',
    id: 'empty',
    title: 'Empty',
  },
  {
    Component: ComponentOverview11,
    component: 'field',
    description:
      'FieldInput、FieldRadio、FieldCheckbox 和 FieldPicker 都是直接组合 Cell 的表单场景。',
    id: 'field',
    title: 'Field',
  },
  {
    Component: ComponentOverview12,
    component: 'floating-panel',
    description:
      'FloatingPanel 通过 selector 汇总拖动、锚点、安全区和主题示例，每次只挂载一个面板。',
    id: 'floating-panel',
    title: 'FloatingPanel',
  },
  {
    Component: ComponentOverview13,
    component: 'gesture',
    description: 'Gesture Handler 与 Reanimated 的基础手势和 UI thread 动画示例。',
    id: 'gesture',
    title: 'Gesture',
  },
  {
    Component: ComponentOverview14,
    component: 'grid',
    description: 'Grid 提供 Vant Mobile 语义的图标、文字和成员操作网格。',
    id: 'grid',
    title: 'Grid',
  },
  {
    Component: ComponentOverview15,
    component: 'icon',
    description: 'Icon 展示图标颜色、尺寸和可触摸图标。',
    id: 'icon',
    title: 'Icon',
  },
  {
    Component: ComponentOverview16,
    component: 'input',
    description: 'Input 汇总基础、密码、数字和多行输入模式。',
    id: 'input',
    title: 'Input',
  },
  {
    Component: ComponentOverview17,
    component: 'loading',
    description:
      'Loading supports distinct circular and spinner indicators, text, layout, and theme slots.',
    id: 'loading',
    title: 'Loading',
  },
  {
    Component: ComponentOverview18,
    component: 'motion',
    description: '统一动画 Hook 和 preset 的可视化验证。',
    id: 'motion',
    title: 'Motion',
  },
  {
    Component: ComponentOverview19,
    component: 'navbar',
    description: 'Vant-style Navbar title, left text and right action examples.',
    id: 'navbar',
    title: 'Navbar',
  },
  {
    Component: ComponentOverview20,
    component: 'notice-bar',
    description: 'NoticeBar 汇总基础、组合内容、滚动、换行、交互、禁用和主题示例。',
    id: 'notice-bar',
    title: 'NoticeBar',
  },
  {
    Component: ComponentOverview21,
    component: 'overlay',
    description: 'Overlay 通过 selector 汇总遮罩、嵌入内容、交互和主题示例，每次只挂载一个遮罩。',
    id: 'overlay',
    title: 'Overlay',
  },
  {
    Component: ComponentOverview22,
    component: 'picker',
    description: 'Picker 汇总弹层、Toolbar、单列、多列、级联、FieldPicker 联动和纯滚轮示例。',
    id: 'picker',
    title: 'Picker',
  },
  {
    Component: ComponentOverview23,
    component: 'popup',
    description: 'Popup 通过 selector 汇总位置、交互、生命周期和主题示例，每次只挂载一个弹层。',
    id: 'popup',
    title: 'Popup',
  },
  {
    Component: ComponentOverview24,
    component: 'portal',
    description: 'Portal 通过 selector 汇总组件式和命令式挂载示例，每次只挂载一个 Portal 案例。',
    id: 'portal',
    title: 'Portal',
  },
  {
    Component: ComponentOverview25,
    component: 'pressable',
    description: '统一 Pressable 的 opacity、scale 和 none 点击反馈。',
    id: 'pressable',
    title: 'Pressable',
  },
  {
    Component: ComponentOverview26,
    component: 'progress',
    description: 'Progress supports tokenized line and circle indicators with animated updates.',
    id: 'progress',
    title: 'Progress',
  },
  {
    Component: ComponentOverview27,
    component: 'provider',
    description: 'Provider 汇总应用级主题和 Portal 上下文入口示例。',
    id: 'provider',
    title: 'Provider',
  },
  {
    Component: ComponentOverview28,
    component: 'radio',
    description: 'Radio 汇总独立选项、分组、button variant、禁用、形状、样式和主题示例。',
    id: 'radio',
    title: 'Radio',
  },
  {
    Component: ComponentOverview29,
    component: 'search',
    description: 'Search 汇总基础、布局扩展、尺寸、输入状态和联系人搜索场景。',
    id: 'search',
    title: 'Search',
  },
  {
    Component: ComponentOverview30,
    component: 'segmented',
    description: 'Segmented 汇总通知、筛选、尺寸、布局、形状和禁用示例。',
    id: 'segmented',
    title: 'Segmented',
  },
  {
    Component: ComponentOverview31,
    component: 'surface',
    description: 'Surface provides a rounded visual container for related mobile content.',
    id: 'surface',
    title: 'Surface',
  },
  {
    Component: ComponentOverview32,
    component: 'swipe-cell',
    description: 'SwipeCell 的微信消息列表、多 action、协调、列表、ref、分组和主题示例。',
    id: 'swipe-cell',
    title: 'SwipeCell',
  },
  {
    Component: ComponentOverview33,
    component: 'switch',
    description: 'Switch supports tokenized sizes, custom values, loading and async confirmation.',
    id: 'switch',
    title: 'Switch',
  },
  {
    Component: ComponentOverview34,
    component: 'tabs',
    description: 'Tabs 汇总 line、card、禁用、横向滚动和受控切换示例。',
    id: 'tabs',
    title: 'Tabs',
  },
  {
    Component: ComponentOverview35,
    component: 'text',
    description: 'Text 汇总基础文本、语义、尺寸和字重示例。',
    id: 'text',
    title: 'Text',
  },
  {
    Component: ComponentOverview36,
    component: 'text-input',
    description: 'TextInput 展示受控文本、可清除文本域和字数限制反馈。',
    id: 'text-input',
    title: 'TextInput',
  },
  {
    Component: ComponentOverview37,
    component: 'theme',
    description: 'Theme 汇总亮暗算法和组件 token 覆盖示例。',
    id: 'theme',
    title: 'Theme',
  },
  {
    Component: ComponentOverview38,
    component: 'time-picker',
    description: 'TimePicker 汇总基础时间、秒、范围、filter、formatter 和 Popup 示例。',
    id: 'time-picker',
    title: 'TimePicker',
  },
  {
    Component: ComponentOverview39,
    component: 'toast',
    description: 'Toast 通过 selector 汇总类型、位置、交互和主题示例，每次只挂载一个提示案例。',
    id: 'toast',
    title: 'Toast',
  },
]
