import type { AliasToken, RadioToken } from '../theme'

export function getRadioToken(token: AliasToken): RadioToken {
  return {
    indicatorSize: token.controlInteractiveSize,
    dotSize: token.controlInteractiveSize / 2,
    borderWidth: token.lineWidth,
    borderRadius: token.borderRadiusSM,
    borderColor: token.colorBorder,
    checkedColor: token.colorPrimary,
    checkmarkColor: token.colorTextLightSolid,
    labelColor: token.colorText,
    disabledColor: token.colorTextDisabled,
    disabledBackground: token.colorFillTertiary,
    disabledLabelColor: token.colorTextDisabled,
    fontSize: token.fontSize,
    lineHeight: token.lineHeight,
    gap: token.paddingXS,
    buttonBg: token.colorBgContainer,
    buttonCheckedBg: token.colorBgContainer,
    buttonCheckedBgDisabled: token.colorBgContainerDisabled,
    buttonCheckedColorDisabled: token.colorTextDisabled,
    buttonColor: token.colorText,
    buttonPaddingHorizontal: token.controlPaddingHorizontal,
    buttonSolidCheckedActiveBg: token.colorPrimaryActive,
    buttonSolidCheckedBg: token.colorPrimary,
    buttonSolidCheckedColor: token.colorTextLightSolid,
    buttonHeight: token.controlHeight,
    buttonHeightSmall: token.controlHeightSM,
    buttonHeightLarge: token.controlHeightLG,
    buttonBorderRadius: token.borderRadiusSM,
    activeOpacity: 0.6,
    disabledOpacity: 0.4,
  }
}
