export const GESTURE_DEFAULT_MIN_DISTANCE = 2
export const GESTURE_DEFAULT_MAX_DISTANCE = 120
export const GESTURE_DEFAULT_SWIPE_THRESHOLD = 0.5
export const GESTURE_DEFAULT_SWIPE_VELOCITY_THRESHOLD = 500
