import type { AliasToken, MapToken } from '../interface'
import { alphaColor } from './colors'

export function createAliasToken(map: MapToken, overrides: Partial<AliasToken> = {}): AliasToken {
  const shadowColor = map.colorShadow

  return {
    ...map,
    colorTextHeading: map.colorText,
    colorTextLabel: map.colorTextSecondary,
    colorTextDescription: map.colorTextTertiary,
    colorIcon: map.colorTextTertiary,
    colorIconHover: map.colorText,
    colorBorderBg: map.colorBgContainer,
    colorSplit: map.colorBorderSecondary,
    colorTextPlaceholder: map.colorTextQuaternary,
    colorTextDisabled: map.colorTextQuaternary,
    colorBgContainerDisabled: map.colorFillTertiary,
    colorBgTextHover: map.colorFillSecondary,
    colorBgTextActive: map.colorFill,
    colorFillAlter: map.colorFillQuaternary,
    colorFillContent: map.colorFillSecondary,
    colorFillContentHover: map.colorFill,
    colorTextLightSolid: map.colorWhite,
    colorHighlight: map.colorError,
    colorErrorAffix: map.colorError,
    colorWarningAffix: map.colorWarning,
    colorErrorOutline: alphaColor(map.colorErrorBg, map.colorBgBase === '#FFFFFF' ? 0.2 : 0.4),
    colorWarningOutline: alphaColor(map.colorWarningBg, map.colorBgBase === '#FFFFFF' ? 0.2 : 0.4),
    fontSizeIcon: map.fontSizeSM,
    fontWeightStrong: 600,
    lineWidthFocus: map.lineWidth * 3,
    controlOutlineWidth: map.lineWidth * 2,
    controlInteractiveSize: map.controlHeight / 2,
    controlItemBgHover: map.colorFillTertiary,
    controlItemBgActive: map.colorPrimaryBg,
    controlItemBgActiveHover: map.colorPrimaryBgHover,
    controlItemBgActiveDisabled: map.colorFill,
    controlTmpOutline: map.colorFillQuaternary,
    controlOutline: alphaColor(map.colorPrimaryBg, 0.2),
    opacityLoading: 0.65,
    linkDecoration: 'none',
    linkHoverDecoration: 'none',
    linkFocusDecoration: 'none',
    controlPaddingHorizontal: 12,
    controlPaddingHorizontalSM: 8,
    paddingXXS: map.sizeXXS,
    paddingXS: map.sizeXS,
    paddingSM: map.sizeSM,
    padding: map.size,
    paddingMD: map.sizeMD,
    paddingLG: map.sizeLG,
    paddingXL: map.sizeXL,
    marginXXS: map.sizeXXS,
    marginXS: map.sizeXS,
    marginSM: map.sizeSM,
    margin: map.size,
    marginMD: map.sizeMD,
    marginLG: map.sizeLG,
    marginXL: map.sizeXL,
    marginXXL: map.sizeXXL,
    boxShadow: `0 6px 16px ${alphaColor(shadowColor, 0.08)}`,
    boxShadowSecondary: `0 3px 6px ${alphaColor(shadowColor, 0.12)}`,
    boxShadowTertiary: `0 1px 2px ${alphaColor(shadowColor, 0.08)}`,
    motion: map.motion,
    ...overrides,
  }
}
