import type { AliasToken, ButtonToken } from '../theme'

export function getButtonToken(token: AliasToken): ButtonToken {
  return {
    heightXS: token.controlHeightXS,
    heightSM: token.controlHeightSM,
    height: token.controlHeight,
    heightLG: token.controlHeightLG,
    borderRadiusXS: token.borderRadiusXS,
    borderRadiusSM: token.borderRadiusSM,
    borderRadius: token.borderRadius,
    borderRadiusLG: token.borderRadiusLG,
    paddingHorizontalXS: token.paddingXXS,
    paddingHorizontalSM: token.paddingSM,
    paddingHorizontal: token.paddingMD,
    paddingHorizontalLG: token.paddingLG,
    contentFontSizeXS: token.fontSizeXS,
    contentFontSizeSM: token.fontSizeSM,
    contentFontSize: token.fontSize,
    contentFontSizeLG: token.fontSizeLG,
    primaryColor: token.colorTextLightSolid,
    primaryBackgroundColor: token.colorPrimary,
    primaryBorderColor: token.colorPrimary,
    primaryPlainBackgroundColor: token.colorPrimaryBg,
    primaryFilledBackgroundColor: token.colorPrimaryBg,
    defaultColor: token.colorText,
    defaultBackgroundColor: token.colorBgContainer,
    defaultBorderColor: token.colorBorder,
    defaultFilledBackgroundColor: token.colorFillTertiary,
    successColor: token.colorTextLightSolid,
    successBackgroundColor: token.colorSuccess,
    successBorderColor: token.colorSuccess,
    successFilledBackgroundColor: token.colorSuccessBg,
    warningColor: token.colorTextLightSolid,
    warningBackgroundColor: token.colorWarning,
    warningBorderColor: token.colorWarning,
    warningFilledBackgroundColor: token.colorWarningBg,
    dangerColor: token.colorTextLightSolid,
    dangerBackgroundColor: token.colorError,
    dangerBorderColor: token.colorError,
    dangerFilledBackgroundColor: token.colorErrorBg,
    borderWidth: token.lineWidth,
    activeOpacity: 0.6,
    disabledOpacity: 0.4,
    iconGap: token.paddingXS,
  }
}
