import type { MapToken } from './maps'

export interface AliasToken extends MapToken {
  colorTextHeading: string
  colorTextLabel: string
  colorTextDescription: string
  colorIcon: string
  colorIconHover: string
  colorBorderBg: string
  colorSplit: string
  colorTextPlaceholder: string
  colorTextDisabled: string
  colorBgContainerDisabled: string
  colorBgTextHover: string
  colorBgTextActive: string
  colorFillAlter: string
  colorFillContent: string
  colorFillContentHover: string
  colorTextLightSolid: string
  colorHighlight: string
  colorErrorAffix: string
  colorWarningAffix: string
  colorErrorOutline: string
  colorWarningOutline: string
  boxShadowSecondary: string
  boxShadowTertiary: string
  boxShadowPopoverArrow: string
  dropShadowPopover: string
  boxShadowCard: string
  boxShadowDrawerRight: string
  boxShadowDrawerLeft: string
  boxShadowDrawerUp: string
  boxShadowDrawerDown: string
  boxShadowTabsOverflowLeft: string
  boxShadowTabsOverflowRight: string
  boxShadowTabsOverflowTop: string
  boxShadowTabsOverflowBottom: string
  fontSizeIcon: number
  fontWeightStrong: number
  lineWidthFocus: number
  controlOutlineWidth: number
  controlInteractiveSize: number
  controlItemBgHover: string
  controlItemBgActive: string
  controlItemBgActiveHover: string
  controlItemBgActiveDisabled: string
  controlTmpOutline: string
  controlOutline: string
  opacityLoading: number
  linkDecoration: 'none'
  linkHoverDecoration: 'none'
  linkFocusDecoration: 'none'
  controlPaddingHorizontal: number
  controlPaddingHorizontalSM: number
  paddingXXS: number
  paddingXS: number
  paddingSM: number
  padding: number
  paddingMD: number
  paddingLG: number
  paddingXL: number
  paddingContentHorizontalLG: number
  paddingContentVerticalLG: number
  paddingContentHorizontal: number
  paddingContentVertical: number
  paddingContentHorizontalSM: number
  paddingContentVerticalSM: number
  marginXXS: number
  marginXS: number
  marginSM: number
  margin: number
  marginMD: number
  marginLG: number
  marginXL: number
  marginXXL: number
  screenXS: number
  screenXSMin: number
  screenXSMax: number
  screenSM: number
  screenSMMin: number
  screenSMMax: number
  screenMD: number
  screenMDMin: number
  screenMDMax: number
  screenLG: number
  screenLGMin: number
  screenLGMax: number
  screenXL: number
  screenXLMin: number
  screenXLMax: number
  screenXXL: number
  screenXXLMin: number
  screenXXLMax: number
  screenXXXL: number
  screenXXXLMin: number
  boxShadow: string
  motion: boolean
  motionDurationFast: number
  motionDurationMid: number
  motionDurationSlow: number
}
