import type { AliasToken, InputToken } from '../theme'

export function getInputToken(token: AliasToken): InputToken {
  return {
    fontSizeSM: token.fontSizeSM,
    fontSize: token.fontSize,
    fontSizeLG: token.fontSizeLG,
    lineHeightSM: token.lineHeightSM + token.paddingXXS,
    lineHeight: token.lineHeight + token.paddingXXS,
    lineHeightLG: token.lineHeightLG + token.paddingXXS,
    textareaLineHeightSM: token.lineHeightSM,
    textareaLineHeight: token.lineHeight,
    textareaLineHeightLG: token.lineHeightLG,
    borderRadius: token.borderRadius,
    paddingHorizontal: token.padding,
    paddingVertical: token.paddingSM - token.paddingXXS / 2,
    textareaPaddingHorizontal: token.padding,
    textareaPaddingVertical: token.paddingXS,
    backgroundColor: token.colorBgContainer,
    borderColor: token.colorBorder,
    activeBorderColor: token.colorPrimary,
    placeholderColor: token.colorTextPlaceholder,
    textColor: token.colorText,
    disabledBackgroundColor: token.colorBgContainerDisabled,
    disabledColor: token.colorTextDisabled,
    selectionColor: token.colorPrimary,
    borderWidth: token.lineWidth,
    clearButtonSize: token.fontSizeLG,
    clearButtonBackgroundColor: token.colorFill,
    clearButtonColor: token.colorTextTertiary,
    prefixColor: token.colorTextSecondary,
    addonColor: token.colorTextSecondary,
    wordLimitColor: token.colorTextTertiary,
    wordLimitFontSize: token.fontSizeSM,
    fontFamily: token.fontFamily,
  }
}
